# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/brcm/rpi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/brcm/rpi/proprietary/vendor/firmware/brcm/BCM4345C0.hcd:vendor/firmware/brcm/BCM4345C0.hcd \
    vendor/brcm/rpi/proprietary/vendor/firmware/brcm/BCM43430A1.hcd:vendor/firmware/brcm/BCM43430A1.hcd \
    vendor/brcm/rpi/proprietary/vendor/lib/hw/gralloc.rpi.so:vendor/lib/hw/gralloc.rpi.so \
    vendor/brcm/rpi/proprietary/vendor/lib/hw/hwcomposer.rpi.so:vendor/lib/hw/hwcomposer.rpi.so \
    vendor/brcm/rpi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:vendor/lib/mediadrm/libwvdrmengine.so
